# Generated by Django 5.0.6 on 2024-06-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('enothi_id', models.CharField(max_length=40)),
                ('ename', models.CharField(max_length=40)),
                ('eemail', models.EmailField(max_length=30)),
                ('edesignation', models.CharField(max_length=40)),
                ('edept', models.CharField(max_length=40)),
                ('esection', models.CharField(max_length=40)),
                ('edivision', models.CharField(default='null_div', max_length=40)),
                ('edirectorate', models.CharField(max_length=40)),
            ],
        ),
    ]
